[general]

# The directory where the SSLO database is located
# This can be an absolute path or relative path.
# A relative path is assumed to be relative to the config.toml file
# All other relative paths in this file are considered to be relative in relation to this.
database_dir="."


[http]

# The port to run the http server onto
port_http=8080

# The port to run the https server onto
port_https=8443

# Path to the SSL cert file in PEM format
ssl_cert="ssl/cert.pem"

# Path to the SSL key file in PEM format
ssl_key="ssl/key.pem"
