openapi: 3.1.0
info:
  title: Los Lobby
  description: API Specification for LOS Lobby
  version: 0.0.1
servers:
  - url: 'https://localhost:8443/api/v0'
components:
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            type: object
            properties:
              summary:
                type: string
              description:
                type: string
paths:
  /login/email:
    post:
      description: "Login with a link that is sent via email"
      responses:
        '200':
          description: "Link sent (if allowed)"
          content:
            application/json:
              schema:
                type: object
                properties:
        '500':
          $ref: '#/components/responses/GeneralError'
  /user/set_name:
    post:
      summary: Change name of current user
      requestBody:
        description: Containing new username
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_name:
                  type: string
      responses:
        '200':
          description: "Name changed"
          content:
            application/json:
              schema:
                type: object
        '401':
          description: "Current user not valid"
        '500':
          description: "Change failed"
