openapi: 3.1.0
info:
  title: Los Lobby
  description: API Specification for LOS Lobby
  version: 0.0.1
servers:
  - url: 'https://localhost:8443/api/v0'
components:
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            type: object
            properties:
              summary:
                type: string
              description:
                type: string
paths:
  /login/password:
    post:
      description: "Login with a link that is sent via email"
      requestBody:
        description: If user_id is set, this is preferred and email is ignored
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                email:
                  type: string
                password:
                  type: string
        '500':
          $ref: '#/components/responses/GeneralError'
  /user/set_name:
    post:
      summary: Change name of current user
      requestBody:
        description: Containing new username
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: "Name changed"
          content:
            application/json:
              schema:
                type: object
        '401':
          $ref: '#/components/responses/GeneralError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /user/set_password:
    post:
      summary: Set/Update password for a user
      requestBody:
        description: Containing current and new passwords
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                new_password:
                  type: string
      responses:
        '200':
          description: "password set"
          content:
            application/json:
              schema:
                type: object
        '401':
          $ref: '#/components/responses/GeneralError'
        '500':
          $ref: '#/components/responses/GeneralError'
